    import = [
      # uncomment the flavour you want below:
      # "~/.config/alacritty/catppuccin-latte.toml"
      # "~/.config/alacritty/catppuccin-frappe.toml"
      # "~/.config/alacritty/catppuccin-macchiato.toml"
      # "~/.config/alacritty/catppuccin-mocha.toml"
      # "~/.config/alacritty/themes/themes/everforest_dark.toml"
      # "~/.config/alacritty/themes/themes/marine_dark.toml"
      "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    ]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u0001v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001L"
key = "Right"
mods = "Command"

[scrolling]
history = 10000
multiplier = 1

[window]
decorations = "buttonless"
opacity = 0.85
option_as_alt = "Both"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 16
y = 16
